name: CI - Maven (HRMS)

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: HRMS

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "11"
          cache: maven

      - name: Build with Maven
        run: mvn -B -DskipTests package

      - name: Run unit tests
        run: mvn -B test

      - name: Archive WAR artifact
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: hrms-war
          path: HRMS/target/*.war
